### ISSUE TITLE
[Question] How to translate this matlab code using your library.

### ISSUE THREAD

**Issue by yqrashawn** [ruohoruotsi/Butterworth-Filter-Design#4]
I'm newb in matlab and c++.

```Matlab
%% High-pass filter linear velocity to remove drift

order = 1;
filtCutOff = 0.1;
[b, a] = butter(order, (2*filtCutOff)/(1/samplePeriod), 'high');
linVelHP = filtfilt(b, a, linVel);
```
a,b are vectors
linVel linVelHP are vectors

**Comment by ruohoruotsi** [comment]
Hi, 
this library is really for designing **high-order** Butterworth IIR & equalization filters. By high-order, I mean more than order 6. If you only need order 1, high pass with a very low cutoff, basically a DC-offset or DC-removal filter. You can do so simply with the following simple one-zero, one pole implementation, as this library is definitely overkill. Cheers.

```
y = x - xm1 + 0.995 * ym1;
xm1 = x;
ym1 = y;
```
Please refer to 

- https://ccrma.stanford.edu/~jos/filters/DC_Blocker_Software_Implementations.html
- https://ccrma.stanford.edu/~jos/filters/DC_Blocker.html

**Comment by ruohoruotsi** [comment]
okay, closing now 👍
